name: Ci-cd to AWS ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: 's3-flask-app-packages1'
  EB_APPLICATION_NAME      : 'My Flask'
  EB_ENVIROMENT_NAME       : 'Prod'
  DEPLOY_PACKAGE_NAME      : 'flask_app_${{ github.sha }}.zip'
  AWS_REGION_NAME          : 'eu-west-3'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v2
    
    - name: create zip 
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment to S3 bucket
      run: aws s3 cp  ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print Happy Message for CI finish
      run: echo 'CI finished successful'

#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
